#!/bin/bash
# Wrapper script to use the bundled Maven
# Get the directory where this script is located
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec "$DIR/apache-maven-3.9.6/bin/mvn" "$@"
