package com.testmanagementtool.service;

import com.testmanagementtool.model.TestAccount;
import com.testmanagementtool.repository.TestAccountRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@SuppressWarnings("null")
public class TestAccountServiceTest {

    @Mock
    private TestAccountRepository repository;

    @InjectMocks
    private TestAccountService service;

    @Test
    void testCreate_GeneratesIdIfMissing() {
        // Arrange
        TestAccount account = new TestAccount();
        account.setUsername("testuser");
        account.setEnvironment("DEV");
        // ID is null initially

        when(repository.save(any(TestAccount.class))).thenAnswer(invocation -> invocation.getArgument(0));

        // Act
        service.create(account);

        // Assert
        ArgumentCaptor<TestAccount> accountCaptor = ArgumentCaptor.forClass(TestAccount.class);
        verify(repository).save(accountCaptor.capture());

        TestAccount capturedAccount = accountCaptor.getValue();
        assertNotNull(capturedAccount.getId(), "ID should be generated by the service before saving");
    }
}
