export const quotes = [
  'Success is not the key to happiness. Happiness is the key to success.',
  'Quality means doing it right when no one is looking. – Henry Ford',
  'Don’t watch the clock; do what it does. Keep going.',
  'The secret of getting ahead is getting started. – Mark Twain',
  'Great things never come from comfort zones.',
  'It always seems impossible until it’s done. – Nelson Mandela',
  'The only way to do great work is to love what you do. – Steve Jobs',
  'Strive not to be a success, but rather to be of value. – Albert Einstein',
  'Well done is better than well said. – Benjamin Franklin',
  'Simplicity is the soul of efficiency. – Austin Freeman',
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Your time is limited, so don't waste it living someone else's life.",
  'The best way to predict the future is to invent it. – Alan Kay',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'What you do today can improve all your tomorrows. – Ralph Marston',
  'It does not matter how slowly you go as long as you do not stop.',
  'Hardships often prepare ordinary people for an extraordinary destiny.',
  'Dream big and dare to fail. – Norman Vaughan',
  'The mind is everything. What you think you become. – Buddha',
  'Life is 10% what happens to me and 90% of how I react to it. – Charles Swindoll',
  'The best time to plant a tree was 20 years ago. The second best time is now.',
  'An unexamined life is not worth living. – Socrates',
  'Eighty percent of success is showing up. – Woody Allen',
  "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
  'I find that the harder I work, the more luck I seem to have. – Thomas Jefferson',
  'Success is walking from failure to failure with no loss of enthusiasm.',
  'The way to get started is to quit talking and begin doing. – Walt Disney',
  'If you want to live a happy life, tie it to a goal, not to people or things.',
  'Never let the fear of striking out keep you from playing the game.',
  "Money and success don't change people; they merely amplify what is already there.",
  "Your time is limited, so don't waste it living someone else's life.",
  'The only person you are destined to become is the person you decide to be.',
  "Whether you think you can or think you can't, you're right. – Henry Ford",
  'The two most important days in your life are the day you are born and the day you find out why.',
  "Everything you've ever wanted is on the other side of fear. – George Addair",
  'Success is not final; failure is not fatal: it is the courage to continue that counts.',
  'Hardships often prepare ordinary people for an extraordinary destiny.',
  'Believe in yourself. You are braver than you think, more talented than you know.',
  'Do not let what you cannot do interfere with what you can do. – John Wooden',
  "Opportunities don't happen, you create them. – Chris Grosser",
  'The future belongs to those who believe in the beauty of their dreams.',
  'Keep your face always toward the sunshine—and shadows will fall behind you.',
  "Don't count the days, make the days count. – Muhammad Ali",
  'The only limit to our realization of tomorrow will be our doubts of today.',
  'The character of a man is his fated fortune. – Heraclitus',
  'A journey of a thousand miles begins with a single step. – Lao Tzu',
  'What we think, we become. – Buddha',
  'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.',
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  'The successful warrior is the average man, with laser-like focus. – Bruce Lee',
  'Courage is grace under pressure. – Ernest Hemingway',
  'Imagination is more important than knowledge. – Albert Einstein',
  "It's not whether you get knocked down, it's whether you get up. – Vince Lombardi",
  'The only way to achieve the impossible is to believe it is possible.',
  'In the middle of every difficulty lies opportunity. – Albert Einstein',
  'Change your thoughts and you change your world. – Norman Vincent Peale',
  'Education is the most powerful weapon which you can use to change the world.',
  'There is no substitute for hard work. – Thomas Edison',
  'Action is the foundational key to all success. – Pablo Picasso',
  'The best revenge is massive success. – Frank Sinatra',
  'The distance between insanity and genius is measured only by success.',
  'Failure is another steppingstone to greatness. – Oprah Winfrey',
  'The only permanent thing in life is change.',
  "Life isn't about finding yourself. Life is about creating yourself.",
  'A person who never made a mistake never tried anything new. – Albert Einstein',
  'Simplicity is the ultimate sophistication. – Leonardo da Vinci',
  'Stay hungry, stay foolish. – Steve Jobs',
  "Your time is precious, so don't waste it on someone else's terms.",
  'Make each day your masterpiece. – John Wooden',
  'Focus on being productive instead of busy. – Tim Ferriss',
  'Great things take time. Be patient and stay persistent.',
  'Your life does not get better by chance, it gets better by change.',
  "Everything you've ever wanted is on the other side of fear.",
  "You don't have to be great to start, but you have to start to be great.",
  'Small daily improvements are the key to staggering long-term results.',
  'Do what you can, with what you have, where you are. – Theodore Roosevelt',
  'Persistence guarantees that results are inevitable.',
  'Every strike brings me closer to the next home run. – Babe Ruth',
  'Difficulties in life are intended to make us better, not bitter.',
  'The most effective way to do it, is to do it. – Amelia Earhart',
  'The successful man will profit from his mistakes and try again in a different way.',
  'The best way to find yourself is to lose yourself in the service of others.',
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "Don't worry about failures, worry about the chances you miss when you don't even try.",
  "Winning isn't everything, but wanting to win is. – Vince Lombardi",
  'It is never too late to be what you might have been. – George Eliot',
  'There are no limits to what you can accomplish, except the limits you place on your own thinking.',
  'Life is a journey, not a destination. – Ralph Waldo Emerson',
  "Try to be a rainbow in someone else's cloud. – Maya Angelou",
  'If you want to achieve greatness stop asking for permission.',
  'Things work out best for those who make the best of how things work out.',
  'To live is the rarest thing in the world. Most people exist, that is all.',
  "You miss 100% of the shots you don't take. – Wayne Gretzky",
  'Keep your eyes on the stars, and your feet on the ground.',
  "Dream as if you'll live forever, live as if you'll die today. – James Dean",
  'Success is how high you bounce when you hit bottom. – George S. Patton',
  'Perfection is not attainable, but if we chase perfection we can catch excellence.',
  'I would rather die of passion than of boredom. – Vincent van Gogh',
  "If you look at what you have in life, you'll always have more.",
  'Happiness depends upon ourselves. – Aristotle',
  "It's not about how many times you fall, but how many times you get back up.",
  'Believe in yourself and all that you are.',
  'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.',
  'The only place where success comes before work is in the dictionary.',
  'Start where you are. Use what you have. Do what you can. – Arthur Ashe',
  'Do not wait to strike till the iron is hot; but make it hot by striking.',
  'Your talent determines what you can do. Your motivation determines how much you are willing to do.',
  'The only way to discover the limits of the possible is to go beyond them into the impossible.',
  'Setting goals is the first step in turning the invisible into the visible.',
  'Logic will get you from A to B. Imagination will take you everywhere. – Albert Einstein',
  "Life is short, and it's up to you to make it sweet. – Sarah Louise Delany",
  'A goal is a dream with a deadline. – Napoleon Hill',
  'Innovation distinguishes between a leader and a follower. – Steve Jobs',
  "Don't let yesterday take up too much of today. – Will Rogers",
  'If you can dream it, you can do it. – Walt Disney',
  'Everything has beauty, but not everyone sees it. – Confucius',
  'The best way out is always through. – Robert Frost',
  'The path to success is to take massive, determined action.',
  'Aim for the moon. If you miss, you may hit a star. – W. Clement Stone',
  'I attribute my success to this: I never gave or took any excuse. – Florence Nightingale',
  'The golden rule of work is to always do more than is expected of you.',
  'Quality is an act, not a habit. – Aristotle',
  'Do one thing every day that scares you. – Eleanor Roosevelt',
  'The purpose of life is to contribute in some way to making things better.',
  'Failure is the condiment that gives success its flavor. – Truman Capote',
  'Change is the end result of all true learning. – Leo Buscaglia',
  'Knowledge speaks, but wisdom listens. – Jimi Hendrix',
  'One today is worth two tomorrows. – Benjamin Franklin',
  'Thinking is the hardest work there is, which is probably the reason why so few engage in it.',
  'Integrity is doing the right thing, even when no one is watching. – C.S. Lewis',
  'The measure of life is not its duration, but its donation.',
  'Motivation is what gets you started. Habit is what keeps you going.',
  "If you're going through hell, keep going. – Winston Churchill",
  'Never ruin an apology with an excuse. – Benjamin Franklin',
  'Success consists of going from failure to failure without loss of enthusiasm.',
  'You must be the change you wish to see in the world. – Mahatma Gandhi',
  'Light tomorrow with today! – Elizabeth Barrett Browning',
  'A warm smile is the universal language of kindness.',
  'Mistakes are proof that you are trying.',
  "It's not what you look at that matters, it's what you see. – Henry David Thoreau",
  'The only thing we have to fear is fear itself. – Franklin D. Roosevelt',
  'Whatever you are, be a good one. – Abraham Lincoln',
  'The best preparation for tomorrow is doing your best today.',
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  'Peace comes from within. Do not seek it without. – Buddha',
  "If you spend too much time thinking about a thing, you'll never get it done.",
  'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
  'Your worth is not measured by your productivity.',
  "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.",
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  'If life were predictable it would cease to be life, and be without flavor.',
  'Spread love everywhere you go. Let no one ever come to you without leaving happier.',
  'Tell me and I forget. Teach me and I remember. Involve me and I learn. – Benjamin Franklin',
  "In the end, it's not the years in your life that count. It's the life in your years.",
  'Life is either a daring adventure or nothing at all. – Helen Keller',
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.',
  'The world is full of magical things, patiently waiting for our senses to grow sharper.',
  'Success usually comes to those who are too busy to be looking for it.',
  "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.",
  'Everything is hard before it is easy.',
  'The power of imagination makes us infinite. – John Muir',
  'Turn your wounds into wisdom. – Oprah Winfrey',
  'The only true wisdom is in knowing you know nothing. – Socrates',
  'We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle',
  'Life is made of ever so many partings welded together. – Charles Dickens',
  "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'",
  'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.',
  'Success is not what you have, but who you are.',
  'A champion is defined not by their wins but by how they can recover when they fall.',
  'The only person you should try to be better than is the person you were yesterday.',
  'Positive anything is better than negative nothing. – Elbert Hubbard',
  "Hard work beats talent when talent doesn't work hard.",
  'Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.',
  'The price of anything is the amount of life you exchange for it. – Henry David Thoreau',
  'Look for the good in every situation.',
  "Success is simple. Do what's right, the right way, at the right time. – Arnold H. Glasow",
  'Kindness is the language which the deaf can hear and the blind can see. – Mark Twain',
  'Gratitude is a powerful catalyst for happiness.',
  'The only way to have a friend is to be one. – Ralph Waldo Emerson',
  'Honesty is the first chapter in the book of wisdom. – Thomas Jefferson',
  'Be kind, for everyone you meet is fighting a harder battle. – Plato',
  "Don't find fault, find a remedy. – Henry Ford",
  'Challenges are what make life interesting and overcoming them is what makes life meaningful.',
  'Growth begins at the end of your comfort zone.',
  'A day without laughter is a day wasted. – Charlie Chaplin',
  'To handle yourself, use your head; to handle others, use your heart. – Eleanor Roosevelt',
  'Life is too short to waste time hating anyone.',
  'If the wind will not serve, take to the oars. – Latin Proverb',
  "Your life is your message to the world. Make sure it's inspiring.",
  'Life is short, but there is always time for courtesy. – Ralph Waldo Emerson',
  'An ounce of patience is worth a pound of brains.',
  'Keep your face to the sunshine and you cannot see a shadow. – Helen Keller',
  'It is not the mountain we conquer, but ourselves. – Edmund Hillary',
  'No masterpiece was ever created by a lazy artist.',
  'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.',
  'The function of leadership is to produce more leaders, not more followers. – Ralph Nader',
  'Learn from yesterday, live for today, hope for tomorrow.',
  'The road to success and the road to failure are almost exactly the same.',
  'If you are not willing to risk the usual, you will have to settle for the ordinary. – Jim Rohn',
  'Success is the sum of small efforts, repeated day-in and day-out. – Robert Collier',
  'All our dreams can come true, if we have the courage to pursue them. – Walt Disney',
  "Don't let what you cannot do interfere with what you can do.",
  "A man who has committed a mistake and doesn't correct it is committing another mistake. – Confucius",
  'True freedom is impossible without a mind made free by discipline. – Mortimer J. Adler',
  "You can't use up creativity. The more you use, the more you have. – Maya Angelou",
  'Everything that you can imagine is real. – Pablo Picasso',
  'There is no great genius without a mixture of madness. – Aristotle',
  'Do not go where the path may lead, go instead where there is no path and leave a trail.',
  'Life is 10% what happens to you and 90% how you respond to it.',
  "Your imagination is your preview of life's coming attractions. – Albert Einstein",
  'Either you run the day, or the day runs you. – Jim Rohn',
  'When you reach the end of your rope, tie a knot in it and hang on. – Franklin D. Roosevelt',
  "Don't breathe to survive; breathe to feel alive.",
  'Strength does not come from winning. Your struggles develop your strengths. – Arnold Schwarzenegger',
  "The harder you work for something, the greater you'll feel when you achieve it.",
  'Dream it. Wish it. Do it.',
  "Success doesn't just find you. You have to go out and get it.",
  'The key to success is to focus on goals, not obstacles.',
  'Wake up with determination. Go to bed with satisfaction.',
  'Do something today that your future self will thank you for.',
  'Little things make big days.',
  "It's going to be hard, but hard does not mean impossible.",
  "Don't stop when you're tired. Stop when you're done.",
  'The only place you find success before work is in the dictionary.',
  'Be the reason someone smiles today.',
  'Great things never come from comfort zones.',
  'Work hard in silence, let your success be your noise. – Frank Ocean',
  'Start each day with a grateful heart.',
  'You are capable of amazing things.',
  "Be so good they can't ignore you. – Steve Martin",
  'Push yourself, because no one else is going to do it for you.',
  'The secret to getting ahead is getting started.',
  "If it's important to you, you'll find a way. If not, you'll find an excuse.",
  "Don't wait for opportunity. Create it.",
  'Success is a journey, not a destination.',
  'Focus on your goals, not your fear.',
  'A little progress each day adds up to big results.',
  'Your only limit is your soul.',
  'Sometimes later becomes never. Do it now.',
  'Great things take time.',
  'Be fearless in the pursuit of what sets your soul on fire.',
  'Believe in yourself.',
  'Everything you need is already inside you.',
  'Let your dreams be your wings.',
  'Stay focused and never give up.',
  "Don't let anyone dull your sparkle.",
  'The best is yet to come.',
  'Make today count.',
  'Work hard, dream big.',
  'Focus on the good.',
  'You got this.',
  'Keep going.',
  'Every moment is a fresh beginning. – T.S. Eliot',
  'Write it on your heart that every day is the best day in the year. – Ralph Waldo Emerson',
  'Whatever you do, do it with all your heart. – Confucius',
  'The only way to do great work is to love what you do.',
  'Success is not in what you have, but in what you give.',
  'Happiness is not something ready made. It comes from your own actions. – Dalai Lama',
  'Be yourself; everyone else is already taken. – Oscar Wilde',
  "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
  'No one can make you feel inferior without your consent. – Eleanor Roosevelt',
  "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
  'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.',
  'Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi',
  'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.',
  'Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.',
  'The fool doth think he is wise, but the wise man knows himself to be a fool. – William Shakespeare',
  "Life is what happens when you're making other plans. – John Lennon",
  'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.',
  'I have found that if you love life, life will love you back. – Arthur Rubinstein',
  'Love the life you live. Live the life you love. – Bob Marley',
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  "Your problem isn't the problem. Your reaction is the problem. – Jack Sparrow",
  "In the end, we only regret the chances we didn't take.",
  "We don't see things as they are, we see them as we are. – Anaïs Nin",
  'The best way to cheer yourself up is to try to cheer somebody else up. – Mark Twain',
  'One of the most beautiful qualities of true friendship is to understand and to be understood.',
  'Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened.',
  'It is during our darkest moments that we must focus to see the light. – Aristotle',
  'What you get by achieving your goals is not as important as what you become by achieving your goals.',
  'Happiness is when what you think, what you say, and what you do are in harmony.',
  "Try to be a rainbow in someone's cloud.",
  'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.',
  "Don't worry about what others think. They're too busy worrying about what you think of them.",
  'The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.',
  'Beauty is not in the face; beauty is a light in the heart. – Kahlil Gibran',
  'A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.',
  'We are all in the gutter, but some of us are looking at the stars. – Oscar Wilde',
  'He who has a why to live can bear almost any how. – Friedrich Nietzsche',
];
